service: mplus
frameworkVersion: "2"

custom:
  config: ${file(./config.${opt:stage}.yml)}

provider:
  name: aws
  region: ap-southeast-1
  memorySize: 256
  timeout: 120
  logRetentionInDays: 90
  role: ${self:custom.config.lambdaRoleArn}
  lambdaHashingVersion: 20201221
  stackName: mplus-data-cleaner-stack

functions:
  data-cleaner:
    name: mplus-${opt:stage}-data-cleaner
    image: ${self:custom.config.ecrImageURI}
    description: Clean MPlus daily EOD data
    events:
      - s3:
          bucket: ${self:custom.config.s3Bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: mplus/
            - suffix: data.csv
          existing: true
